name: searchfield
description: A highly customizable, simple and easy to use flutter Widget to add a searchfield to your Flutter Application. This Widget allows you to search and select from list of suggestions.
version: 0.9.9
homepage: https://github.com/maheshmnj/searchfield
repository: https://github.com/maheshmnj/searchfield
issue_tracker: https://github.com/maheshmnj/searchfield/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.1
