name: searchfield
description: A highly customizable, simple and easy to use AutoComplete widget for your Flutter app
version: 1.2.4
homepage: https://github.com/maheshj01/searchfield
repository: https://github.com/maheshj01/searchfield
issue_tracker: https://github.com/maheshj01/searchfield/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.1
