name: searchfield
description: A highly customizable, simple and easy to use AutoComplete widget for your Flutter app
version: 2.0.0-dev.1
homepage: https://github.com/maheshj01/searchfield
repository: https://github.com/maheshj01/searchfield
issue_tracker: https://github.com/maheshj01/searchfield/issues
funding:
  - https://github.com/sponsors/maheshj01/
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.1
